pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'alpine:3.10'
                }
            }                            
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }            
    }
}
